package generator_test

// Spot-checks for the DDL parity slice (CREATE-table constraints, ALTER TABLE/VIEW/INDEX,
// DROP): hand-built expression trees generated with the exact arg-shapes Part 1 pinned in
// expressions/kinds.go, verified against `python3 -c "import sqlglot; ...sql(dialect=...)"`
// on the pinned reference (.reference/sqlglot-v30.12.0, sqlglot==30.12.0) rather than
// through ParseOne, since these node kinds don't require the parser to be finished.
//
// Oracle transcript (PYTHONPATH=.reference/sqlglot-v30.12.0 python3):
//
//	>>> sqlglot.parse_one("CREATE TABLE t (a INT CONSTRAINT pk PRIMARY KEY)").sql()
//	'CREATE TABLE t (a INT CONSTRAINT pk PRIMARY KEY)'
//	>>> sqlglot.parse_one("CREATE TABLE t (a INT PRIMARY KEY DESC)").sql()
//	'CREATE TABLE t (a INT PRIMARY KEY DESC)'
//	>>> sqlglot.parse_one("CREATE TABLE t (a INT GENERATED ALWAYS AS IDENTITY "
//	...     "(START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 100 CYCLE))").sql()
//	'CREATE TABLE t (a INT GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 100 CYCLE))'
//	>>> sqlglot.parse_one("CREATE TABLE t (a INT GENERATED BY DEFAULT AS IDENTITY)").sql()
//	'CREATE TABLE t (a INT GENERATED BY DEFAULT AS IDENTITY)'
//	>>> sqlglot.parse_one("ALTER TABLE t ADD COLUMN a INT").sql(dialect="mysql")
//	'ALTER TABLE t ADD COLUMN a INT'
//	>>> sqlglot.parse_one("ALTER TABLE db.t RENAME TO db.t2").sql(dialect="postgres")
//	'ALTER TABLE db.t RENAME TO t2'
//	>>> sqlglot.parse_one("ALTER TABLE t MODIFY COLUMN a INT").sql(dialect="mysql")
//	'ALTER TABLE t MODIFY COLUMN a INT'
//	>>> sqlglot.parse_one("ALTER TABLE t ALTER COLUMN a SET DATA TYPE INT").sql()
//	'ALTER TABLE t ALTER COLUMN a SET DATA TYPE INT'
//	>>> sqlglot.parse_one("DROP TABLE IF EXISTS t CASCADE").sql()
//	'DROP TABLE IF EXISTS t CASCADE'
//	>>> sqlglot.parse_one("ALTER TABLE t SET (fillfactor = 70)").sql(dialect="postgres")
//	'ALTER TABLE t SET (fillfactor = 70)'
import (
	"testing"

	"github.com/ridi/sqlglot-go/dialects"
	exp "github.com/ridi/sqlglot-go/expressions"
	"github.com/ridi/sqlglot-go/generator"
)

func genSQL(t *testing.T, d *dialects.Dialect, e exp.Expression) string {
	t.Helper()
	if d == nil {
		d = dialects.Base()
	}
	got, err := generator.New(d, generator.Options{}).Generate(e)
	if err != nil {
		t.Fatalf("Generate() error: %v", err)
	}
	return got
}

func numLit(n string) exp.Expression { return exp.Literal(exp.Args{"this": n, "is_string": false}) }

func TestColumnConstraintSQL(t *testing.T) {
	cases := []struct {
		name string
		node exp.Expression
		want string
	}{
		{
			"unnamed primary key",
			exp.ColumnConstraint(exp.Args{"kind": exp.PrimaryKeyColumnConstraint(exp.Args{})}),
			"PRIMARY KEY",
		},
		{
			"named constraint",
			exp.ColumnConstraint(exp.Args{"this": exp.ToIdentifier("pk"), "kind": exp.PrimaryKeyColumnConstraint(exp.Args{})}),
			"CONSTRAINT pk PRIMARY KEY",
		},
		{
			"primary key desc",
			exp.PrimaryKeyColumnConstraint(exp.Args{"desc": true}),
			"PRIMARY KEY DESC",
		},
		{
			"primary key asc",
			exp.PrimaryKeyColumnConstraint(exp.Args{"desc": false}),
			"PRIMARY KEY ASC",
		},
		{
			"not null",
			exp.NotNullColumnConstraint(exp.Args{}),
			"NOT NULL",
		},
		{
			"allow null",
			exp.NotNullColumnConstraint(exp.Args{"allow_null": true}),
			"NULL",
		},
		{
			"unique",
			exp.UniqueColumnConstraint(exp.Args{}),
			"UNIQUE",
		},
		{
			"auto increment",
			exp.AutoIncrementColumnConstraint(exp.Args{}),
			"AUTO_INCREMENT",
		},
		{
			"check enforced",
			exp.CheckColumnConstraint(exp.Args{
				"this":     exp.GT(exp.Args{"this": exp.Column(exp.Args{"this": exp.ToIdentifier("a")}), "expression": numLit("0")}),
				"enforced": true,
			}),
			"CHECK (a > 0) ENFORCED",
		},
		{
			// python: GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 100 CYCLE)
			"generated always identity with sequence opts",
			exp.GeneratedAsIdentityColumnConstraint(exp.Args{
				"this": true, "start": numLit("1"), "increment": numLit("1"),
				"minvalue": numLit("1"), "maxvalue": numLit("100"), "cycle": true,
			}),
			"GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 100 CYCLE)",
		},
		{
			"generated by default identity",
			exp.GeneratedAsIdentityColumnConstraint(exp.Args{"this": false}),
			"GENERATED BY DEFAULT AS IDENTITY",
		},
		{
			"generated always as bare identity",
			exp.GeneratedAsIdentityColumnConstraint(exp.Args{"this": true}),
			"GENERATED ALWAYS AS IDENTITY",
		},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			if got := genSQL(t, nil, tc.node); got != tc.want {
				t.Fatalf("got %q, want %q", got, tc.want)
			}
		})
	}
}

func TestComputedColumnConstraintDialects(t *testing.T) {
	// python (base):     AS b + 1
	// python (mysql):    GENERATED ALWAYS AS (b + 1) VIRTUAL / STORED
	// python (postgres): GENERATED ALWAYS AS (b + 1) STORED
	b := func() exp.Expression {
		return exp.Add(exp.Args{"this": exp.Column(exp.Args{"this": exp.ToIdentifier("b")}), "expression": numLit("1")})
	}
	cases := []struct {
		name string
		d    *dialects.Dialect
		node exp.Expression
		want string
	}{
		{"base persisted", nil, exp.ComputedColumnConstraint(exp.Args{"this": b(), "persisted": true}), "AS b + 1 PERSISTED"},
		{"base bare", nil, exp.ComputedColumnConstraint(exp.Args{"this": b()}), "AS b + 1"},
		{"mysql stored", dialects.MySQL(), exp.ComputedColumnConstraint(exp.Args{"this": b(), "persisted": true}), "GENERATED ALWAYS AS (b + 1) STORED"},
		{"mysql virtual", dialects.MySQL(), exp.ComputedColumnConstraint(exp.Args{"this": b()}), "GENERATED ALWAYS AS (b + 1) VIRTUAL"},
		{"postgres always stored", dialects.Postgres(), exp.ComputedColumnConstraint(exp.Args{"this": b()}), "GENERATED ALWAYS AS (b + 1) STORED"},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			if got := genSQL(t, tc.d, tc.node); got != tc.want {
				t.Fatalf("got %q, want %q", got, tc.want)
			}
		})
	}
}

func TestAlterFamilySQL(t *testing.T) {
	table := func(name string) exp.Expression { return exp.Table(exp.Args{"this": exp.ToIdentifier(name)}) }
	colDef := func(name string, dtype exp.DType) exp.Expression {
		return exp.ColumnDef(exp.Args{"this": exp.ToIdentifier(name), "kind": exp.DataType(exp.Args{"this": dtype})})
	}

	cases := []struct {
		name string
		d    *dialects.Dialect
		node exp.Expression
		want string
	}{
		{
			// python (base):  ALTER TABLE t ADD COLUMN a INT
			"alter add column base",
			nil,
			exp.Alter(exp.Args{"this": table("t"), "kind": "TABLE", "actions": []exp.Expression{colDef("a", exp.DTypeInt)}}),
			"ALTER TABLE t ADD COLUMN a INT",
		},
		{
			// python (mysql): ALTER TABLE t ADD COLUMN a INT
			"alter add column mysql",
			dialects.MySQL(),
			exp.Alter(exp.Args{"this": table("t"), "kind": "TABLE", "actions": []exp.Expression{colDef("a", exp.DTypeInt)}}),
			"ALTER TABLE t ADD COLUMN a INT",
		},
		{
			// python (base): ALTER TABLE t ALTER COLUMN a SET DATA TYPE INT
			"alter column set data type base",
			nil,
			exp.Alter(exp.Args{"this": table("t"), "kind": "TABLE", "actions": []exp.Expression{
				exp.AlterColumn(exp.Args{"this": exp.ToIdentifier("a"), "dtype": exp.DataType(exp.Args{"this": exp.DTypeInt})}),
			}}),
			"ALTER TABLE t ALTER COLUMN a SET DATA TYPE INT",
		},
		{
			// python (mysql): ALTER TABLE t MODIFY COLUMN a INT
			"alter column dtype mysql rewrite",
			dialects.MySQL(),
			exp.Alter(exp.Args{"this": table("t"), "kind": "TABLE", "actions": []exp.Expression{
				exp.AlterColumn(exp.Args{"this": exp.ToIdentifier("a"), "dtype": exp.DataType(exp.Args{"this": exp.DTypeInt})}),
			}}),
			"ALTER TABLE t MODIFY COLUMN a INT",
		},
		{
			// python (mysql): ALTER TABLE t MODIFY COLUMN a INT
			"modify column mysql",
			dialects.MySQL(),
			exp.Alter(exp.Args{"this": table("t"), "kind": "TABLE", "actions": []exp.Expression{
				exp.ModifyColumn(exp.Args{"this": colDef("a", exp.DTypeInt)}),
			}}),
			"ALTER TABLE t MODIFY COLUMN a INT",
		},
		{
			// python (postgres): ALTER TABLE db.t RENAME TO t2 (db-qualifier stripped)
			"alter rename postgres strips db",
			dialects.Postgres(),
			exp.Alter(exp.Args{
				"this": exp.Table(exp.Args{"this": exp.ToIdentifier("t"), "db": exp.ToIdentifier("db")}),
				"kind": "TABLE",
				"actions": []exp.Expression{exp.AlterRename(exp.Args{
					"this": exp.Table(exp.Args{"this": exp.ToIdentifier("t2"), "db": exp.ToIdentifier("db")}),
				})},
			}),
			"ALTER TABLE db.t RENAME TO t2",
		},
		{
			// python (base): ALTER TABLE t RENAME TO t2
			"alter rename base keeps to",
			nil,
			exp.Alter(exp.Args{"this": table("t"), "kind": "TABLE", "actions": []exp.Expression{
				exp.AlterRename(exp.Args{"this": table("t2")}),
			}}),
			"ALTER TABLE t RENAME TO t2",
		},
		{
			// python (mysql): ALTER TABLE t RENAME t2 (no TO keyword)
			"alter rename mysql omits to",
			dialects.MySQL(),
			exp.Alter(exp.Args{"this": table("t"), "kind": "TABLE", "actions": []exp.Expression{
				exp.AlterRename(exp.Args{"this": table("t2")}),
			}}),
			"ALTER TABLE t RENAME t2",
		},
		{
			// python (postgres): ALTER TABLE t SET (fillfactor = 70)
			"alter set postgres",
			dialects.Postgres(),
			exp.Alter(exp.Args{"this": table("t"), "kind": "TABLE", "actions": []exp.Expression{
				exp.AlterSet(exp.Args{"expressions": []exp.Expression{
					exp.EQ(exp.Args{"this": exp.Column(exp.Args{"this": exp.ToIdentifier("fillfactor")}), "expression": numLit("70")}),
				}}),
			}}),
			"ALTER TABLE t SET (fillfactor = 70)",
		},
		{
			// python (base): DROP TABLE IF EXISTS t CASCADE
			"drop table if exists cascade",
			nil,
			exp.Drop(exp.Args{"this": table("t"), "kind": "TABLE", "exists": true, "cascade": true}),
			"DROP TABLE IF EXISTS t CASCADE",
		},
		{
			// python (mysql): ALTER TABLE t DROP PRIMARY KEY
			"drop primary key",
			dialects.MySQL(),
			exp.Alter(exp.Args{"this": table("t"), "kind": "TABLE", "actions": []exp.Expression{exp.DropPrimaryKey(exp.Args{})}}),
			"ALTER TABLE t DROP PRIMARY KEY",
		},
		{
			// python (base): ALTER TABLE t RENAME COLUMN a TO b
			"rename column",
			nil,
			exp.Alter(exp.Args{"this": table("t"), "kind": "TABLE", "actions": []exp.Expression{
				exp.RenameColumn(exp.Args{"this": exp.ToIdentifier("a"), "to": exp.ToIdentifier("b")}),
			}}),
			"ALTER TABLE t RENAME COLUMN a TO b",
		},
		{
			// python (mysql): ALTER TABLE t RENAME INDEX a TO b
			"rename index",
			dialects.MySQL(),
			exp.Alter(exp.Args{"this": table("t"), "kind": "TABLE", "actions": []exp.Expression{
				exp.RenameIndex(exp.Args{"this": exp.ToIdentifier("a"), "to": exp.ToIdentifier("b")}),
			}}),
			"ALTER TABLE t RENAME INDEX a TO b",
		},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			if got := genSQL(t, tc.d, tc.node); got != tc.want {
				t.Fatalf("got %q, want %q", got, tc.want)
			}
		})
	}
}

func TestForeignKeyPrimaryKeyReferenceSQL(t *testing.T) {
	// python: CREATE TABLE t (a INT, CONSTRAINT fk FOREIGN KEY (a) REFERENCES other (id)
	// ON DELETE CASCADE) -> the ON DELETE clause is nested Reference.options (parenthesized
	// column list is itself a Schema, hence the space before "(id)": schema_sql joins
	// `this + " " + columns`).
	fk := exp.ForeignKey(exp.Args{
		"expressions": []exp.Expression{exp.Column(exp.Args{"this": exp.ToIdentifier("a")})},
		"reference": exp.Reference(exp.Args{
			"this": exp.Schema(exp.Args{
				"this":        exp.Table(exp.Args{"this": exp.ToIdentifier("other")}),
				"expressions": []exp.Expression{exp.Column(exp.Args{"this": exp.ToIdentifier("id")})},
			}),
			"options": []exp.Expression{exp.Var(exp.Args{"this": "ON DELETE CASCADE"})},
		}),
	})
	want := "FOREIGN KEY (a) REFERENCES other (id) ON DELETE CASCADE"
	if got := genSQL(t, nil, fk); got != want {
		t.Fatalf("got %q, want %q", got, want)
	}

	pk := exp.PrimaryKey(exp.Args{"expressions": []exp.Expression{exp.Column(exp.Args{"this": exp.ToIdentifier("a")})}})
	if got, want := genSQL(t, nil, pk), "PRIMARY KEY (a)"; got != want {
		t.Fatalf("got %q, want %q", got, want)
	}
}

func TestIndexColumnConstraintSQL(t *testing.T) {
	// python: sqlglot.parse_one("CREATE TABLE t (a INT, INDEX idx USING BTREE (a))",
	//   read="mysql").sql(dialect="mysql")
	//   -> 'CREATE TABLE t (a INT, INDEX idx USING BTREE (a))'
	node := exp.IndexColumnConstraint(exp.Args{
		"this":        exp.ToIdentifier("idx"),
		"expressions": []exp.Expression{exp.Column(exp.Args{"this": exp.ToIdentifier("a")})},
		"index_type":  exp.Var(exp.Args{"this": "BTREE"}),
	})
	want := "INDEX idx USING BTREE (a)"
	if got := genSQL(t, dialects.MySQL(), node); got != want {
		t.Fatalf("got %q, want %q", got, want)
	}
}
