package generator

import "github.com/sjincho/sqlglot-go/expressions"

var dispatch map[expressions.Kind]func(*Generator, expressions.Expression) string

func init() {
	dispatch = map[expressions.Kind]func(*Generator, expressions.Expression) string{
		expressions.KindExpression:          (*Generator).expressionSQL,
		expressions.KindColumn:              (*Generator).columnSQL,
		expressions.KindLiteral:             (*Generator).literalSQL,
		expressions.KindIdentifier:          (*Generator).identifierSQL,
		expressions.KindStar:                (*Generator).starSQL,
		expressions.KindAlias:               (*Generator).aliasSQL,
		expressions.KindAliases:             (*Generator).aliasesSQL,
		expressions.KindDot:                 (*Generator).dotSQL,
		expressions.KindNull:                (*Generator).nullSQL,
		expressions.KindBoolean:             (*Generator).booleanSQL,
		expressions.KindVar:                 (*Generator).varSQL,
		expressions.KindParen:               (*Generator).parenSQL,
		expressions.KindNeg:                 (*Generator).negSQL,
		expressions.KindNot:                 (*Generator).notSQL,
		expressions.KindAdd:                 (*Generator).addSQL,
		expressions.KindSub:                 (*Generator).subSQL,
		expressions.KindMul:                 (*Generator).mulSQL,
		expressions.KindDiv:                 (*Generator).divSQL,
		expressions.KindMod:                 (*Generator).modSQL,
		expressions.KindEQ:                  (*Generator).eqSQL,
		expressions.KindNEQ:                 (*Generator).neqSQL,
		expressions.KindNullSafeEQ:          (*Generator).nullSafeEQSQL,
		expressions.KindGT:                  (*Generator).gtSQL,
		expressions.KindGTE:                 (*Generator).gteSQL,
		expressions.KindLT:                  (*Generator).ltSQL,
		expressions.KindLTE:                 (*Generator).lteSQL,
		expressions.KindAnd:                 (*Generator).andSQL,
		expressions.KindOr:                  (*Generator).orSQL,
		expressions.KindBitwiseAnd:          (*Generator).bitwiseAndSQL,
		expressions.KindBitwiseOr:           (*Generator).bitwiseOrSQL,
		expressions.KindBitwiseXor:          (*Generator).bitwiseXorSQL,
		expressions.KindDPipe:               (*Generator).dpipeSQL,
		expressions.KindBetween:             (*Generator).betweenSQL,
		expressions.KindIs:                  (*Generator).isSQL,
		expressions.KindLike:                (*Generator).likeSQL,
		expressions.KindILike:               (*Generator).ilikeSQL,
		expressions.KindIn:                  (*Generator).inSQL,
		expressions.KindSelect:              (*Generator).selectSQL,
		expressions.KindFrom:                (*Generator).fromSQL,
		expressions.KindJoin:                (*Generator).joinSQL,
		expressions.KindTable:               (*Generator).tableSQL,
		expressions.KindTableAlias:          (*Generator).tableAliasSQL,
		expressions.KindWhere:               (*Generator).whereSQL,
		expressions.KindGroup:               (*Generator).groupSQL,
		expressions.KindOrder:               (*Generator).orderSQL,
		expressions.KindLimit:               (*Generator).limitSQL,
		expressions.KindOffset:              (*Generator).offsetSQL,
		expressions.KindHint:                (*Generator).hintSQL,
		expressions.KindBlock:               (*Generator).blockSQL,
		expressions.KindPlaceholder:         (*Generator).placeholderSQL,
		expressions.KindTuple:               (*Generator).tupleSQL,
		expressions.KindWith:                (*Generator).withSQL,
		expressions.KindCTE:                 (*Generator).cteSQL,
		expressions.KindRecursiveWithSearch: (*Generator).recursiveWithSearchSQL,
		expressions.KindUnion:               (*Generator).setOperationsSQL,
		expressions.KindExcept:              (*Generator).setOperationsSQL,
		expressions.KindIntersect:           (*Generator).setOperationsSQL,
		expressions.KindSubquery:            (*Generator).subquerySQL,
		expressions.KindHaving:              (*Generator).havingSQL,
		expressions.KindQualify:             (*Generator).qualifySQL,
		expressions.KindCube:                (*Generator).cubeSQL,
		expressions.KindRollup:              (*Generator).rollupSQL,
		expressions.KindGroupingSets:        (*Generator).groupingSetsSQL,
		expressions.KindOrdered:             (*Generator).orderedSQL,
		expressions.KindDistinct:            (*Generator).distinctSQL,
		expressions.KindWindow:              (*Generator).windowSQL,
		expressions.KindWindowSpec:          (*Generator).windowSpecSQL,
		expressions.KindFilter:              (*Generator).filterSQL,
		expressions.KindLimitOptions:        (*Generator).limitOptionsSQL,
		expressions.KindFetch:               (*Generator).fetchSQL,
		expressions.KindCase:                (*Generator).caseSQL,
		expressions.KindIf:                  (*Generator).ifSQL,
		expressions.KindExists:              (*Generator).existsSQL,
		expressions.KindAny:                 (*Generator).anySQL,
		expressions.KindAll:                 (*Generator).allSQL,
		expressions.KindNullSafeNEQ:         (*Generator).nullSafeNEQSQL,
		expressions.KindAnonymous:           (*Generator).anonymousSQL,
		expressions.KindLog:                 (*Generator).logSQL,
		expressions.KindInsert:              (*Generator).insertSQL,
		expressions.KindUpdate:              (*Generator).updateSQL,
		expressions.KindDelete:              (*Generator).deleteSQL,
		expressions.KindMerge:               (*Generator).mergeSQL,
		expressions.KindWhen:                (*Generator).whenSQL,
		expressions.KindWhens:               (*Generator).whensSQL,
		expressions.KindOnConflict:          (*Generator).onConflictSQL,
		expressions.KindReturning:           (*Generator).returningSQL,
		expressions.KindCreate:              (*Generator).createSQL,
		expressions.KindSchema:              (*Generator).schemaSQL,
		expressions.KindCommand:             (*Generator).commandSQL,
		expressions.KindPivot:               (*Generator).pivotSQL,
		expressions.KindLateral:             (*Generator).lateralSQL,
		expressions.KindValues:              (*Generator).valuesSQL,
		expressions.KindColumnDef:           (*Generator).columnDefSQL,
		expressions.KindDataType:            (*Generator).dataTypeSQL,
		expressions.KindDataTypeParam:       (*Generator).dataTypeParamSQL,
		expressions.KindCast:                (*Generator).castSQL,
		expressions.KindTryCast:             (*Generator).tryCastSQL,
		expressions.KindExtract:             (*Generator).extractSQL,
		expressions.KindTrim:                (*Generator).trimSQL,
		expressions.KindCeil:                (*Generator).ceilFloorSQL,
		expressions.KindFloor:               (*Generator).ceilFloorSQL,
		expressions.KindUnnest:              (*Generator).unnestSQL,
		expressions.KindBracket:             (*Generator).bracketSQL,
		expressions.KindLock:                (*Generator).lockSQL,
		expressions.KindPreWhere:            (*Generator).preWhereSQL,
		expressions.KindCluster:             (*Generator).clusterSQL,
		expressions.KindDistribute:          (*Generator).distributeSQL,
		expressions.KindSort:                (*Generator).sortSQL,
		expressions.KindWithinGroup:         (*Generator).withinGroupSQL,
		expressions.KindIgnoreNulls:         (*Generator).ignoreNullsSQL,
		expressions.KindRespectNulls:        (*Generator).respectNullsSQL,
		expressions.KindPivotAny: func(g *Generator, e expressions.Expression) string {
			return "ANY" + g.sqlKey(e, "this")
		},
		expressions.KindPivotAlias: (*Generator).pivotAliasSQL,
		expressions.KindInterval:   (*Generator).intervalSQL,
		expressions.KindIntervalSpan: func(g *Generator, e expressions.Expression) string {
			return g.sqlKey(e, "this") + " TO " + g.sqlKey(e, "expression")
		},
		expressions.KindJSONCast:  (*Generator).jsonCastSQL,
		expressions.KindArrayAgg:  (*Generator).arrayAggSQL,
		expressions.KindArraySize: (*Generator).arraySizeSQL,
		expressions.KindInitcap:   (*Generator).initcapSQL,
		expressions.KindHex:       (*Generator).hexSQL,
		expressions.KindDateAdd:   (*Generator).dateAddSQL,
	}
}
